version: '3.8'
services:


  users:
    build: ./users
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    container_name: UsersAPI
    volumes:
      - ./users:/app
    environment: 
      - USER-DB_NAME=users
      - USER_DB_USER=postgres
      - USER_DB_PASSWORD=postgres
      - USER_DB_HOST=usersDB


  jobs:
    build: ./jobs
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    container_name: JobsAPI
    volumes:
      - ./jobs:/app
    environment:
      - JOB_DB_NAME=jobs
      - JOB_DB_USER=postgres
      - JOB_DB_PASSWORD=postgres
      - JOB_DB_HOST=jobsDB



  blog:
    build: ./blog
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8003"
    ports:
      - "8003:8003"
    container_name: BlogAPI
    volumes:
      - ./blog:/app
    environment:
      - BLOG_DB_NAME=blog
      - BLOG_DB_USER=postgres
      - BLOG_DB_PASSWORD=postgres
      - BLOG_DB_HOST=blogDB



  userDB:
    image: postgres:15
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - users-data:/var/lib/postgresql/data


  jobsDB:
    image: postgres:15
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - jobs-data:/var/lib/postgresql/data



  blogDB:
    image: postgres:15
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    volumes:
      - blog-data:/var/lib/postgresql/data

volumes:
  blog-data:
  jobs-data:
  users-data:
